version: '3.8'

services:
  db:
    image: postgres:17
    container_name: doner_db
    environment:
      POSTGRES_USER: doner_user
      POSTGRES_PASSWORD: 211204
      POSTGRES_DB: doner_cafe
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dumpBD:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build:
      context: ./server/nest-back-cafe
    container_name: doner_backend
    env_file:
      - ./server/nest-back-cafe/.env
    environment:
      DB_HOST: doner_db
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./client
    container_name: doner_frontend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: doner_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  pgdata:
