server {
    listen 80;
    server_name vkrsitefood.ru www.vkrsitefood.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vkrsitefood.ru www.vkrsitefood.ru;

    ssl_certificate     /etc/letsencrypt/live/vkrsitefood.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vkrsitefood.ru/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_max_temp_file_size 0;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /images/ {
        proxy_pass http://backend:3000/images/;
    }
}