server {
    listen 80;
    server_name vkrsitefood.ru www.vkrsitefood.ru localhost;

    # Настройки для раздачи собранного React-кода из папки
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Если маршрут не найден, перенаправляем на index.html (важно для React Router)
        try_files $uri $uri/ /index.html;
    }

    # Проксирование всех запросов к API на бэкенд
    # Проксирование картинок бэкенда
    location /api/ {
    proxy_pass http://doner_backend:3000/;
    }


}
